- dotnet/BeakPeekApi.Tests/Helpers/BirdInfoHelperTest.cs
- dotnet/BeakPeekApi/Helpers/BirdInfoHelper.cs
- dotnet/BeakPeekApi/Models/BirdInfoModel.cs
Fixed the test for fetching images from flickr by streamlining the api call into a singular call in stead of a call for the images and a call for the owner info
> Fixed the test for fetching images from flickr

- docker-compose.yml
- dotnet/BeakPeekApi.Tests/BeakPeekApi.Tests.csproj
- dotnet/BeakPeekApi.Tests/Controllers/BirdControllerTest.cs
- dotnet/BeakPeekApi.Tests/Controllers/BirdInfoControllerTest.cs
- dotnet/BeakPeekApi.Tests/Helpers/BirdInfoHelperTest.cs
- dotnet/BeakPeekApi.Tests/packages.lock.json
- dotnet/BeakPeekApi/.gitignore
- dotnet/BeakPeekApi/BeakPeekApi.csproj
- dotnet/BeakPeekApi/Controllers/BirdController.cs
- dotnet/BeakPeekApi/Controllers/BirdInfoController.cs
- dotnet/BeakPeekApi/Helpers/BirdInfoHelper.cs
- dotnet/BeakPeekApi/Migrations/20240716100820_BeakPeekDB_migration.Designer.cs
- dotnet/BeakPeekApi/Migrations/20240716100820_BeakPeekDB_migration.cs
- dotnet/BeakPeekApi/Models/BirdInfoDto.cs
- dotnet/BeakPeekApi/Models/BirdInfoModel.cs
- dotnet/BeakPeekApi/Program.cs
- dotnet/BeakPeekApi/appsettings.json
- dotnet/BeakPeekApi/packages.lock.json
- Endpoints to get the number of birds in a province or in the country
- Bird info controller to get images and information about a bird given its name 
- Bird info helper that makes requests to Wikipedia and Flickr for images and information
- tests for all endpoints and helpers
> Bird info and number of birds endpoints

- beakpeek/devtools_options.yaml
- beakpeek/lib/Controller/DB/achievements_provider.dart
- beakpeek/lib/Controller/DB/database_calls.dart
- beakpeek/lib/Model/achievement.dart
- beakpeek/lib/Model/user_profile_function.dart
- beakpeek/lib/View/UserProfile/user_profile.dart
- beakpeek/test/UserProfile/user_profile_function_test.dart
> Achivement Finished

- beakpeek/lib/Controller/Main/routing_data.dart
- beakpeek/lib/Model/bird.dart
- beakpeek/lib/Model/bird_page_functions.dart
- beakpeek/lib/View/Home/bird_page.dart
- beakpeek/lib/View/Home/bird_quiz.dart
- beakpeek/lib/View/Home/bird_sheet.dart
- beakpeek/lib/View/Home/home.dart
- beakpeek/lib/View/Home/main.dart
Just integrated the bird page and all of the maps as well as the quiz
> Integrated the quiz and maps with the bird page

- beakpeek/lib/Controller/Azure/login.dart
- beakpeek/lib/Controller/DB/database_calls.dart
- beakpeek/lib/Model/BirdInfo/bird_search_functions.dart
- beakpeek/lib/Model/Globals/globals.dart
- beakpeek/lib/View/Home/Searching/filterable_searchbar.dart
- beakpeek/lib/View/Home/Searching/local_search.dart
- beakpeek/lib/View/Sightings/sightings.dart
- beakpeek/lib/View/offline_message.dart
Added custom component to display offline/ error messages
> Added offline error component

- dotnet/BeakPeekApi/Controllers/BirdController.cs
> :twisted_rightwards_arrows: Fix null refernce for bird

- dotnet/BeakPeekApi/Models/Pentad.cs
- dotnet/BeakPeekApi/Models/Province.cs
Fixed an error with the DTO in the api that was stopping the heat map
> 🛠️ fix: Fixed the getBirdPentads api call

- beakpeek/android/app/src/main/AndroidManifest.xml
- beakpeek/lib/Controller/Azure/login.dart
- beakpeek/lib/Model/UserProfile/achievement.dart
- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/config_azure.dart
- beakpeek/lib/main.dart
- beakpeek/pubspec.lock
- beakpeek/pubspec.yaml
- dotnet/UserApi/UserApi/Controllers/UserRolesController.cs
- :sparkles: Users now sign in via the user api
- :sparkles: Users data is now stored locally in a model
- :wrench: App now properly redirects to when signing in
> :twisted_rightwards_arrows: Adding integration for frontend to use user api

- beakpeek/lib/Controller/DB/database_calls.dart
- beakpeek/lib/Controller/DB/life_list_provider.dart
- beakpeek/lib/Model/BirdInfo/bird.dart
- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/View/Achievements/achievements_page.dart
- beakpeek/lib/View/Settings/settings_page.dart
- beakpeek/lib/View/UserProfile/user_profile.dart
- beakpeek/lib/main.dart
- beakpeek/linux/flutter/generated_plugin_registrant.cc
- beakpeek/linux/flutter/generated_plugins.cmake
- beakpeek/macos/Flutter/GeneratedPluginRegistrant.swift
- beakpeek/test/Database/database_calls_test.dart
- beakpeek/windows/flutter/generated_plugin_registrant.cc
- beakpeek/windows/flutter/generated_plugins.cmake
Added SQL queries as well as better optimum prime
> ✨Introduce new features. 🎨Improve structure / format of the code. 

- dotnet/UserApi/UserApi/Controllers/UserController.cs
- :sparkles: Added an endpoint that deletes the user that is authenticated using the received bearer token
- :memo: The endpoint is accessible via the route GET `/User/Delete` with the correct bearer token
> :sparkles: Added an endpoint to delete a user

- beakpeek/lib/Model/BirdInfo/bird_pentad.dart
- beakpeek/lib/View/Home/home.dart
- beakpeek/lib/View/Map/bird_map.dart
- beakpeek/lib/View/Map/heat_map.dart
- beakpeek/lib/View/UserProfile/color_palette.dart
Reverts COS301-SE-2024/BeakPeek#293
> Revert "Reworked the location to only work in South Africa"

- beakpeek/lib/Controller/Main/routing_data.dart
- beakpeek/lib/View/Home/home.dart
- beakpeek/lib/View/Settings/settings_page.dart
- beakpeek/lib/View/Sightings/sightings.dart
- beakpeek/lib/View/UserProfile/user_profile.dart
> 🛠️ fix:Routing fixes update 13 files

- beakpeek/lib/Controller/DB/life_list_provider.dart
- beakpeek/lib/Model/BirdInfo/bird.dart
- beakpeek/lib/View/Settings/edit_user_profile.dart
- beakpeek/lib/View/Settings/settings_page.dart
- beakpeek/lib/View/Sightings/sighting_widgets.dart
- beakpeek/lib/View/Sightings/sightings.dart
> Dev/feat/fixes Added images to sighting

- beakpeek/lib/Model/UserProfile/user_model.dart
- Fixed user login due to not handling nulls in the user model properly
> :twisted_rightwards_arrows: Fix User login

- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/pubspec.lock
- dotnet/UserApi/UserApi/Controllers/UserController.cs
- dotnet/UserApi/UserApi/Data/ApplicationDbContext.cs
- dotnet/UserApi/UserApi/Migrations/20240928094154_UserAchievments.Designer.cs
- dotnet/UserApi/UserApi/Migrations/20240928094154_UserAchievments.cs
- dotnet/UserApi/UserApi/Models/AppUser.cs
- dotnet/UserApi/UserApi/Program.cs
- :sparkles: Added the ability to track a users achievements and a users progress towards an achievement
- :sparkles: Added an endpoint that accepts a user json object to be used to update a users profile online
> :twisted_rightwards_arrows:  Add user updating and achievement tracking

- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/View/Settings/edit_user_profile.dart
- Users can now update their profile from within the mobile app
> ✨ Feat: Connected the edit profile page to the online api

- dotnet/UserApi/UserApi/Migrations/20240928125838_AchievementIcons.Designer.cs
- dotnet/UserApi/UserApi/Migrations/20240928125838_AchievementIcons.cs
- dotnet/UserApi/UserApi/Models/Achievement.cs
- dotnet/UserApi/UserApi/Views/Achievement/Create.cshtml
- dotnet/UserApi/UserApi/Views/Achievement/Details.cshtml
- dotnet/UserApi/UserApi/Views/Achievement/Edit.cshtml
- dotnet/UserApi/UserApi/Views/Achievement/Index.cshtml
- Added category property to achievements
- Added icon name property to achievements
> :sparkles: Added the ability to interchangebly use images or icon names and also categories

- dotnet/UserApi/UserApi/Areas/Identity/Pages/Account/Login.cshtml
- dotnet/UserApi/UserApi/Areas/Identity/Pages/Account/Login.cshtml.cs
- dotnet/UserApi/UserApi/Controllers/UserController.cs
- dotnet/UserApi/UserApi/Models/AppUser.cs
- Fixed a problem with after changing username not being able to login
- The problem cam about because signing in is actually done by username
- You should now to be able to sign in with either or
> 🛠️ Fix: Fixed a problem with logging in after changing username

- beakpeek/lib/Controller/Azure/login.dart
- beakpeek/lib/Model/UserProfile/achievement.dart
- beakpeek/lib/Model/UserProfile/achievment_list.dart
- beakpeek/lib/Model/UserProfile/user_achievment.dart
- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/View/Achievements/achievements_page.dart
- beakpeek/lib/config_azure.dart
- beakpeek/pubspec.lock
- beakpeek/pubspec.yaml
- Added it so that achievements are stored locally
- Added it so that achievements are fetched from the API
- Added a merge flow to get updated achievement progress
- Made it so that achievements is loaded asyncronously
> ✨ Feat: Added achievement logic for the flutter frontent

- beakpeek/lib/Controller/Azure/login.dart
- beakpeek/lib/Controller/Main/routing_data.dart
- beakpeek/lib/Model/BirdInfo/bird_search_functions.dart
- beakpeek/lib/Model/nav.dart
- beakpeek/lib/View/Bird/bird_page.dart
- beakpeek/lib/View/Home/GuestUserBlock/guest_user_block.dart
- beakpeek/lib/View/Home/Searching/filterable_searchbar.dart
- beakpeek/lib/View/Home/Searching/local_search.dart
- beakpeek/lib/View/Home/home.dart
- beakpeek/lib/View/Login/landing_tab_2.dart
- beakpeek/lib/View/Login/terms_and_conditions_popup.dart
- beakpeek/lib/View/Map/bird_sheet.dart
- beakpeek/lib/View/Map/heat_map_info.dart
- beakpeek/lib/View/Quiz/bird_quiz.dart
- beakpeek/lib/View/Sightings/sighting_widgets.dart
- beakpeek/lib/View/UserProfile/user_profile.dart
Dont delete in case more issues
@mattgbotha Please style GuestUserBlock
> 🛠️ fix:Routing fixes and Guest User

- beakpeek/lib/config_azure.dart
- beakpeek/pubspec.lock
- dotnet/UserApi/UserApi/Areas/Identity/Pages/Account/Manage/Index.cshtml
- dotnet/UserApi/UserApi/Controllers/HomeController.cs
- dotnet/UserApi/UserApi/Views/Home/Index.cshtml
- dotnet/UserApi/UserApi/Views/Home/Privacy.cshtml
- dotnet/UserApi/UserApi/Views/Shared/_Layout.cshtml
- Redirect will now work for mobile with the return URL of '%2FHome%2FMobile' instead of always redirecting to the mobile app when on mobile and on the home page
> 🛠️ Fix: Fixed a problem with redirecting to mobile

- beakpeek/lib/Controller/Azure/login.dart
- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/View/Login/landing_tab_2.dart
- beakpeek/lib/View/Login/terms_and_conditions_popup.dart
- beakpeek/lib/View/Settings/settings_page.dart
- dotnet/UserApi/UserApi/Controllers/UserController.cs
- :sparkles: Added a logout button to the settings page that clears local data and takes the user to the login page
- :lock: Allowed anonymous access to get all achievements 
- :hammer_and_wrench: Fixed a problem with users not being navigated to the home context when logging in directly after accepting Ts&Cs
> :twisted_rightwards_arrows: Fixing user login, adding logout

- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/View/Settings/edit_user_profile.dart
- dotnet/UserApi/UserApi/Migrations/20240929085522_HighScore.Designer.cs
- dotnet/UserApi/UserApi/Migrations/20240929085522_HighScore.cs
- dotnet/UserApi/UserApi/Models/AppUser.cs
- :sparkles: Added a property to user model on the frontend for highscore
- :sparkles: Added a property to user model on the backend for highscore
> ✨ Feat: Added a highscore property for users on the api and the frontend

- beakpeek/lib/Controller/Azure/login.dart
- beakpeek/lib/Model/UserProfile/achievement.dart
- beakpeek/lib/Model/UserProfile/achievment_list.dart
- beakpeek/lib/Model/UserProfile/user_model.dart
- beakpeek/lib/View/Achievements/achievements_page.dart
- beakpeek/pubspec.lock
- :sparkles: Implemented logic for updating progress towards an achievement
- :sparkles: Added Quiz Master achievement progress logic
> :sparkles: Feat Added achievement control and Quiz master achievement logic

- beakpeek/lib/View/Home/Searching/filterable_searchbar.dart
- beakpeek/lib/View/Map/heat_map.dart
Fixed the monthly filter on the heat map and the routing from the search bar to the bird page
> 🛠️ fix: Fixed the routing and heat map

- beakpeek/lib/View/Bird/bird_page.dart
- beakpeek/lib/View/Home/home.dart
- beakpeek/lib/View/Settings/edit_user_profile.dart
- beakpeek/lib/View/Settings/settings_page.dart
- beakpeek/lib/View/UserProfile/color_palette.dart
- beakpeek/lib/View/UserProfile/user_profile.dart
- beakpeek/pubspec.lock
Changes done to various UI elements:
- Edit profile moved to profile page and removed from settings.
- Other unnecessary settings removed.
- Improved bird page styling.
> 🔀 Merge branches: Merging dev/feat/filters into development.

- beakpeek/lib/View/Quiz/bird_quiz.dart
- beakpeek/lib/View/Settings/edit_user_profile.dart
- beakpeek/lib/View/UserProfile/user_profile.dart
Final UI changes made for the evening
- Quiz page popup text fixed
- Text now wraps in user's bio
- Save button on edit profile sticks to bottom of the page
> 🔀 Merge branches: Merging dev/feat/final_ui_fixes into development

- beakpeek/lib/Controller/Home/sound_controller.dart
- beakpeek/lib/View/Home/GuestUserBlock/guest_user_block.dart
- beakpeek/lib/View/Login/terms_and_conditions_popup.dart
- beakpeek/lib/View/Sightings/sightings.dart
Updated guest UI to look better:
- Styled page that asks user to log in when viewing inaccessible pages on guest account.
- Styled terms and conditions popup some more.
- Fixed popup in dark mode.
> 💄UI Update: Updated guest UI - merging into development

- dotnet/BirdApi/BeakPeekApi/Program.cs
- dotnet/UserApi/UserApi/Areas/Identity/Pages/Account/Login.cshtml
- dotnet/UserApi/UserApi/Areas/Identity/Pages/Account/Manage/Email.cshtml
- dotnet/UserApi/UserApi/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
- dotnet/UserApi/UserApi/Views/Shared/_Layout.cshtml
- :wrench: Removed auto import of birds to ensure no removed birds are re-added
- :fire: Removed unimplemented options from the User Management portal
- :sparkles: Added a show password button when logging in
- :lipstick: Removed unused urls and improved spacing on the login page
- :wrench: Fixed a problem with the Nav bar not showing when looking at external logins
> :twisted_rightwards_arrows: Adding User registration fixes and changes

- beakpeek/lib/View/Map/heat_map.dart
- Weird heat map UI glitch fixed
> 🐛 Fix: Fixed heat map UI problem - merging into dev

- beakpeek/lib/View/Map/heat_map.dart
- beakpeek/lib/View/UserProfile/color_palette.dart
Clicking on the legend takes you to the color palette page
> :sparkles: feat: Colour Palette page entry from heat map

- dotnet/UserApi/UserApi/Controllers/AchievementController.cs
- dotnet/UserApi/UserApi/Controllers/AppUserController.cs
- dotnet/UserApi/UserApi/Views/AppUser/Delete.cshtml
- :hammer_and_wrench: Fixed the delete button on the users page
- :hammer_and_wrench: Fixed the delete button the achievement page
> 🛠️ Fix: Fixed the delete button on the admin portal

- dotnet/UserApi/UserApi/Views/AppUser/Index.cshtml
- :lipstick: Changed user management view to only show relevant information
> 💄 UI: Changed the user management portal 

- beakpeek/lib/View/Achievements/achievements_page.dart
- beakpeek/lib/View/Home/Searching/filterable_searchbar.dart
- beakpeek/lib/View/Settings/edit_user_profile.dart
- beakpeek/lib/View/Sightings/sightings.dart
- Changed help content on achievements page
- Changed help content on sightings page
- Save button on edit profile now redirects back to profile
> 🐛 Fix: Fixed help content and a route

- dotnet/BirdApi/BeakPeekApi/Helpers/BirdImageHelper.cs
Changed the backend to fetch images by their Scientific Name rather than their common name
> 🔀 Changed the backend to fetch images by Scientific Name

- doc/Awards/Algorithms/algorithms.tex
- doc/Awards/Datascience/datascience.tex
Added the Heat map, Bird map and Life list documentation to the Data Science and Algorithms laTex documents
> 🔀 Added the awards documentation

- .github/workflows/deploy_dotnet.yml
- .github/workflows/update_birds.yml
- dotnet/BirdApi/BeakPeekApi.Tests/Controllers/ImportControllerTest.cs
- dotnet/BirdApi/BeakPeekApi/Controllers/ImportController.cs
- dotnet/BirdApi/BeakPeekApi/Helpers/CsvImporter.cs
- dotnet/BirdApi/BeakPeekApi/appsettings.Development.json
- scripts/bash/auto_import.sh
- scripts/bash/download_regions.sh
- ✨ Added and fixed endpoints on the bird api needed for data automation
- 👷 Added a script for download the bird data from SABAP
- 🚀 Added a workflow that uses the bird data script to download the bird and pentad data from SABAP and also filter out invalid birds
- 🚀 Added a job onto the bird api deployment pipeline to use the bird data updates
> ✨ Added automations needed to import birds from SABAB

- .github/workflows/update_birds.yml
- scripts/bash/auto_import.sh
- 🛠️ Fixed a problem with how the script figures out if it is running as a test or as a production script
> 🛠️ Fixed some problems with running the correct tasks when importing birds

- .github/workflows/coverage.yml
- .github/workflows/dotnet.yml
- .github/workflows/flutter.yml
- 🚀 Refactored flutter workflow to use artifacts for coverage file when possible and upload dotnet coverage as well
- 🚀 Refactored dotnet workflow to work similarily to the flutter workflow
- 🚀 Added a workflow to build, test and upload coverage reports for both the dotnet and flutter sides of the project
> 🚀 Added a workflow that tests and uploads coverage reports for the backend and frontend
